# Target Python versions
target-version = "py311"

# Include these directories for checking
src = ["mlx_engine", "tests"]

# Exclude files/directories from checking
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    "build",
    "dist"
]

# Allow unused imports in __init__.py files
[per-file-ignores]
"__init__.py" = ["F401"]
