name: Lint

on:
  push:
    branches: [ ** ]
  pull_request:
    branches: [ ** ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          
      - name: Check formatting
        run: ruff format --check . --verbose
        
      - name: Run linter
        run: ruff check . --verbose